// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.PowerUp2018.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc1735.PowerUp2018.subsystems.*;

/**
 *
 */
public class AutoSwitch2x extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoSwitch2x() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	// reset the gyro because we don't know how much it drifted between power-on and the start of the match.
    	// Assuming we are square with the Driverstation Wall, this should properly define the Zero Degree point...
    	addSequential(new ResetGyro());
    	// Drive over to the switch
    	addSequential(new DriveWithPID(154)); //drive forward (in inches) until we are even with the end of the switch
    	// Turn to face the switch
    	addSequential(new ConditionalTurn(-90, DriveTrain.kAbsolute));
    	// Drive  up to the switch fence
    	addSequential(new DriveWithPID(1));
    	//Deploy the clamp
    	addSequential(new MoveClamps(1), 0.5); // direction, timeout
    	// Raise the elevator to delivery position
    	addSequential(new ElevatorwithPID(20)); // in inches
    	//Final approach to the scale
    	addSequential(new DriveWithPID(5));
    	// Drop the cube
    	addSequential(new OpenClamps());
    	// Back up a bit and turn around
    	addSequential(new DriveWithPID(-5));
    	//Turn back downfield
    	addSequential(new ConditionalTurn(0, DriveTrain.kAbsolute));
    	// Drive past the cube
    	addSequential(new DriveWithPID(60));
    	// turn and drive even with the cube
    	addSequential(new ConditionalTurn(-90, DriveTrain.kAbsolute));
    	addSequential(new DriveWithPID(32));
    	// Turn to face the cube
    	addSequential(new ConditionalTurn(-175, DriveTrain.kAbsolute));
    	// Center on the cube
    	addSequential(new ConditionalTurn(0, DriveTrain.kCamera)); // angle is not used; it is grabbed from the camera
    	// Drive to the cube
    	addSequential(new DriveWithPID(DriveTrain.kUseCamera));
    	// Grab the cube
    	addSequential(new CloseClamps());
    	// Raise the elevator to switch delivery position
    	addSequential(new ElevatorwithPID(20)); //Something more than 18.75 inches... TBD
    	// Drive forward until the bumpers touch.  Bumpers are about 6" deep, so cube-bumper is about 6"
    	addSequential(new DriveWithPID(6));
    	// Drop the cube
    	addSequential( new OpenClamps());
    	// Done!

    } 
}
