// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.PowerUp2018.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc1735.PowerUp2018.Robot;
import org.usfirst.frc1735.PowerUp2018.subsystems.*;

/**
 *
 */
public class AutoSwitch1x extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutoSwitch1x() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    	// Goal:  we are directly in front of our own switch plate.  Drive forward and deliver the cube.
    	// reset the gyro because we don't know how much it drifted between power-on and the start of the match.
    	// Assuming we are square with the Driverstation Wall, this should properly define the Zero Degree point...
    	addSequential(new ResetGyro());
    	//Deploy the clamps
    	addSequential(new ClampsDeploy(), Clamps.kClampsDeployTimeout); // direction, timeout
    	// Raise the elevator to delivery position
    	addSequential(new ElevatorMove(1), Elevator.kTimeLoadToSwitch); //ElevatorwithPID(20)); // in inches
    	//Final approach to the scale
    	addSequential(new DriveWithPID(90), 3); //97->105
    	// We overshoot so the first drive is shorter than needed
    	// Drive a second time to the final location
    	addSequential(new DriveWithPID(12), 2); //97->105

    	// Drop the cube
    	addSequential(new OpenClamps());
    	// Done!
    	
    	
    } 
}
