// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.PowerUp2018.subsystems;

import org.usfirst.frc1735.PowerUp2018.Robot;
import org.usfirst.frc1735.PowerUp2018.RobotMap;
import org.usfirst.frc1735.PowerUp2018.commands.*;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.command.Subsystem;

import com.ctre.phoenix.ParamEnum;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.RemoteFeedbackDevice;
import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard; // Because RobotBuilder keeps leaving it out of the autogenerated code
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
/**
 *
 */
public class DriveTrain extends Subsystem implements PIDOutput {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX leftFollower = RobotMap.driveTrainLeftFollower;
    private final WPI_TalonSRX rightFollower = RobotMap.driveTrainRightFollower;
    private final WPI_TalonSRX leftMotor = RobotMap.driveTrainLeftMotor;
    private final WPI_TalonSRX rightMotor = RobotMap.driveTrainRightMotor;
    private final DifferentialDrive differentialDrive1 = RobotMap.driveTrainDifferentialDrive1;
    private final WPI_VictorSPX leftFollowerVictor = RobotMap.driveTrainLeftFollowerVictor;
    private final WPI_VictorSPX rightFollowerVictor = RobotMap.driveTrainRightFollowerVictor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveWithJoysticks());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	// Print the current gyro heading
        SmartDashboard.putNumber(   "Raw Angle",         Robot.ahrs.getAngle()); //cumulative angle over time
        SmartDashboard.putNumber(   "Rotation Rate",     Robot.ahrs.getRate()); // Rotation rate in deg/sec
        SmartDashboard.putNumber(   "Yaw",               Robot.ahrs.getYaw()); //-180 to +180 from last zeroed yaw setting
        
        //Print the acceleration vector(s)
        SmartDashboard.putNumber(   "Y Accel",           Robot.ahrs.getWorldLinearAccelY());    
        
        //Grab the Limelight data stream
        double x = tx.getDouble(0);
        SmartDashboard.putNumber("Cube Angle", x);
        double y = ty.getDouble(0);
        double area = ta.getDouble(0);
        double cameraAngle = 56.0;
        double targetHeight = 5.5;
        double cameraHeight = 44.5;
        double d;
        d = ((Math.tan(Math.toRadians(cameraAngle + y))) * (cameraHeight - targetHeight));
        SmartDashboard.putNumber("Cube Distance", d);

    }

    public void drivetrainInit() {
    	// Do initialization that cannot be done in the constructor because robot.init isn't executed yet so we don't have a gyro instance.
    	
    	//-----------------------------
    	// Software PID Subsystem Initialization
    	//-----------------------------
    	//PID values.values  F is feed-forward for maintaining rotational velocity.
    	// The last two args are input source and output object (our PIDwrite() function)
        drivelineController = new PIDController(kLargeTurnP, kLargeTurnI, kLargeTurnD, kLargeTurnF, Robot.ahrs, this);
        drivelineController.setInputRange(-180.0f, 180.0f); // WHY IS THIS -180 to +180 RATHER THAN 0-360????
        drivelineController.setOutputRange(-0.75, 0.75); // What is the allowable range of values to send to the output (our motor rotation)
        drivelineController.setAbsoluteTolerance(kToleranceDegrees); // How close do we have to be in order to say we have reached the target?
        // Robot can spin in full circle so angle might wrap from 0 to 360.
        // 'Continuous' allows us to follow that wrap to get from 359 to 0, rather than going counterclockwise a full circle to get there.
        drivelineController.setContinuous(true);        
        /* Add the PID Controller to the Test-mode dashboard, allowing manual  */
        /* tuning of the Turn Controller's P, I and D coefficients.            */
        /* Typically, only the P value needs to be modified.                   */
        LiveWindow.addActuator("DriveSystem", "RotateController", drivelineController);
        
        //Expose these to the SmartDashboard (plus some debug turn parameters) for DEBUG ONLY:
    	SmartDashboard.putBoolean("TurnAbsolute", false); // Assume relative
    	SmartDashboard.putNumber("TurnAngle", 0); // Assuming relative, zero means no change.
    	SmartDashboard.putNumber("TurnP", kLargeTurnP);
    	SmartDashboard.putNumber("TurnI", kLargeTurnI);
    	SmartDashboard.putNumber("TurnD", kLargeTurnD);
    	SmartDashboard.putNumber("TurnErr", kToleranceDegrees);
    	
    	//-----------------------------
    	//Hook up to the Limelight
    	//-----------------------------
        table = NetworkTableInstance.getDefault().getTable("limelight");
        tx = table.getEntry("tx");
        ty = table.getEntry("ty");
        ta = table.getEntry("ta");
        
    	//-----------------------------
        // Talon open- and closed-loop configuration
        //-----------------------------

        // Chose the sensor and direction
    	leftMotor.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 0); // extra args are:  primary closed loop, timeout in ms
    	leftMotor.setSensorPhase(true); //Assume inversion
    	rightMotor.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 0);
    	rightMotor.setSensorPhase(true); //Assume inversion.
    	// Followers do not have sensors.
    	
    	// Voltage compensation mode should make 100% output request scale to 12V regardless of battery voltage.
    	// (if battery voltage is less than 12v it will just put all available voltage out)
    	leftMotor.enableVoltageCompensation(true);
    	rightMotor.enableVoltageCompensation(true);
    	
    	// Set the desired 100% at 12V
    	leftMotor.configVoltageCompSaturation(12.0, 0);
    	rightMotor.configVoltageCompSaturation(12.0, 0);
    	
    	// Encoder setup:  Since we are using the CTRE Mag Encoders, we do not
    	// need to configure anything further
    	
    	// Closed-loop PID initialization/configuration
    	//
    	// See full code example at https://github.com/CrossTheRoadElec/FRC-Examples-STEAMWORKS/blob/master/JAVA_MotionMagicExample/src/org/usfirst/frc/team217/robot/Robot.java

    	// set the peak and nominal outputs, -1 to 1 in percentage of nominal voltage (even if battery voltage is higher)
    	leftMotor.configNominalOutputForward(0.0, 0);
    	leftMotor.configNominalOutputReverse(-0.0, 0);
    	leftMotor.configPeakOutputForward(1.0,0);
    	leftMotor.configPeakOutputReverse(-1.0,0);
    	rightMotor.configNominalOutputForward(0.0, 0);
    	rightMotor.configNominalOutputReverse(-0.0, 0);
    	rightMotor.configPeakOutputForward(1.0,0);
    	rightMotor.configPeakOutputReverse(-1.0,0);

    	// set closed loop gains in slot0 - see documentation
    	leftMotor.selectProfileSlot(0,0);
    	rightMotor.selectProfileSlot(0,0);

    	// set acceleration and vcruise velocity - see documentation
    	leftMotor.configMotionCruiseVelocity(2700, 0); // 2700 encoder units per 100ms interval is about 395 RPM
    	rightMotor.configMotionCruiseVelocity(2700, 0);

    	// It's not clear how the MotionAcceleration and the ClosedloopRamp differ...
    	leftMotor.configMotionAcceleration(8100, 0); //want to get to full speed in 1/3 sec, so triple the velocity
    	rightMotor.configMotionAcceleration(8100, 0); 

    	// Set the closed loop ramp as well (time in seconds to full speed; timeout)
    	leftMotor.configClosedloopRamp(0.333, 0); //want to get to full speed in 1/3 sec
    	leftMotor.configOpenloopRamp(0.333, 0);
    	rightMotor.configClosedloopRamp(0.333, 0);
    	rightMotor.configOpenloopRamp(0.333, 0);


    	//Set the closed-loop allowable error.  Empirically on no-load, error was <50 units.
    	leftMotor.configAllowableClosedloopError(0, (int) kToleranceDistUnits, 0); // index, err, timeout in ms
    	rightMotor.configAllowableClosedloopError(0, (int) kToleranceDistUnits, 0); // index, err, timeout in ms
    	
    	// Some packet frames default to updating at 160ms, which is waaaay too slow for our 20ms DS periodic interval!
		// CTRE recommends that you set relevant frame periods to be at least as fast as periodic rate-- their example uses:
		leftMotor.setStatusFramePeriod(StatusFrameEnhanced.Status_13_Base_PIDF0, 10, 0);
		leftMotor.setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 10, 0);
		rightMotor.setStatusFramePeriod(StatusFrameEnhanced.Status_13_Base_PIDF0, 10, 0);
		rightMotor.setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 10, 0);


    	// Throw a lot of settings up on the SmartDashboard...
    	SmartDashboard.putNumber("Cruise SpeedDir", 2700); // speed in units per 100ms (2745 is full speed)
    	SmartDashboard.putNumber("Cruise Dist", 72); // inches (DriveWithPID will convert to encoder ticks)
    	SmartDashboard.putNumber("Cruise Accel", 8100); //1/3 sec to get to full speed
    	SmartDashboard.putNumber("Cruise R Accel", 10000);     	//Temporary to allow setting left vs right accel separately
    	SmartDashboard.putNumber("P", kDistP);
    	SmartDashboard.putNumber("I", kDistI);
    	SmartDashboard.putNumber("D", kDistD);
    	SmartDashboard.putNumber("F", kDistF);
    	}
    
    // We need to initialize followers based on whether we are selecting the practice bot or the competition bot.
    // This can't be done in robotInit because the dashboard hasn't come up yet, so we pull this code out to be run later
    // in the teleop/autonomous init routines.
    public void lateInit() {
    	//  We only want to call this routine once per match.
    	// if we started the robot in teleop we need it to run, but if we ran autonomous first and then teleop, it shouldn't run twice
    	if (m_lateInitHasRun)
    		return;
    	else {
    		m_lateInitHasRun = true;
    		//System.out.println("lateInit is being run...");
    		
    		// Tell the followers to follow the appropriate master.
    		// We won't talk to the followers beyond this except to invert the right side when switching between open loop
    		// (where WPILIB inverts them) and closed loop (Where we invert them)
    		// We also switch betwen coast (open loop) and brake (closed loop) for the followers.
    		// We have different follower models between Practice and Competition robots, so choose carefully:
    		if (SmartDashboard.getBoolean("PracticeBot", false)) {
    			// Practice
    			leftFollower.follow(leftMotor);
    			rightFollower.follow(rightMotor);
    			leftFollower.setSafetyEnabled(false);
    			rightFollower.setSafetyEnabled(false);
    		}
    		else {
    			// Competition
    			leftFollowerVictor.follow(leftMotor);
    			rightFollowerVictor.follow(rightMotor);        	
    			leftFollowerVictor.setSafetyEnabled(false);
    			rightFollowerVictor.setSafetyEnabled(false);
    		}

    		// Default to be in "drive by joystick" mode
    		// if we are going into Autonomous, the first Command will properly set the operating mode so we're still ok
    		setOpenLoopMode();
    	} // if !m_lateInitHasRun
    }
    
    public void setOpenLoopMode() {
    	// This function does the Talon configuration changes to allow operation in an open-loop mode
    	// (Which is what we use for joystick control)
    	
    	// Which robot are we using?
    	boolean isPractice = SmartDashboard.getBoolean("PracticeBot", false);
    	
    	//In this mode, we use the DifferentialDrive WPI library... which does the right motor inversion in software, so we have to turn the hardware inversion off here:
    	rightMotor.setInverted(false);
        if (isPractice) {
        	// Practice
        	rightFollower.setInverted(false);
        }
        else {
        	// Competition
        	rightFollowerVictor.setInverted(false);       	
        }

    	// Set our mode to be the open-loop drive-by-joystick behavior:
    	leftMotor.set(ControlMode.PercentOutput, 0); // Mode, setpoint
    	rightMotor.set(ControlMode.PercentOutput, 0); // Mode, setpoint

    	// Put the Talons in "Coast" mode
    	//leftMotor.setNeutralMode(NeutralMode.Coast);
    	//rightMotor.setNeutralMode(NeutralMode.Coast);
        if (isPractice) {
        	// Practice
        	//leftFollower.setNeutralMode(NeutralMode.Coast);
        	//rightFollower.setNeutralMode(NeutralMode.Coast);
        }
        else {
        	// Competition
        	//leftFollowerVictor.setNeutralMode(NeutralMode.Coast);
        	//rightFollowerVictor.setNeutralMode(NeutralMode.Coast);
        }
    }

    public void setPIDMode() {
    	// This function does the Talon configuration changes to allow operation in a closed-loop PID mode.
    	// this allows us to use the Talon HW PID for positional control,
    	// and if in MotionMagic mode, it will also obey the trapezoidal motion profile for acceleration
    	// and maximum velocity.

    	// Which robot are we using?
    	boolean isPractice = SmartDashboard.getBoolean("PracticeBot", false);

    	// In closed-loop mode we talk to the motor controllers directly, and don't get the inversion of the right-hand motors that's implemented
    	// in the WPIlib DifferentialDrive class.  So, we have to invert the motor controller hardware directly:
    	rightMotor.setInverted(true);
        if (isPractice) {
        	//Practice
        	rightFollower.setInverted(true);
        }
        else {
        	// Competition
        	rightFollowerVictor.setInverted(true);
        }
    	
       	//Set the mode to Magic (for the master; slaves match for now).  Second arg is the setpoint.
        leftMotor.set(ControlMode.Position, 0);
        rightMotor.set(ControlMode.Position, 0);
   	
    	// Put the Talons in "Brake" mode for better accuracy
    	leftMotor.setNeutralMode(NeutralMode.Brake);
    	rightMotor.setNeutralMode(NeutralMode.Brake);
        if (isPractice) {
        	// Practice
        	leftFollower.setNeutralMode(NeutralMode.Brake);
        	rightFollower.setNeutralMode(NeutralMode.Brake);
        }
        else {
        	// Competition
        	leftFollowerVictor.setNeutralMode(NeutralMode.Brake);
        	rightFollowerVictor.setNeutralMode(NeutralMode.Brake);
        }
 
    	// Zero out the relative sensors
        leftMotor.setSelectedSensorPosition(0,0,0); // position, PIDidx (0= normal), timeout in ms
        rightMotor.setSelectedSensorPosition(0,0,0); // position, PIDidx (0= normal), timeout in ms
   	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void arcadeDrive(double moveValue, double rotateValue, boolean squaredInputs) {
    	// This function is a wrapper in case we need to do anything special before calling the final arcadeDrive.
    	// The WPI library assumes the turn parameter is clockwise = positive.
    	// New for 2018, the WPILIB drivetrain is redesigned and assumes positive == forwards so no Y-axis sign shenanigans anymore! 
    	//SmartDashboard.putNumber("MotorOut", rotateValue);
    	
    	differentialDrive1.arcadeDrive(moveValue, rotateValue, squaredInputs);
    }
    
    public void tankDrive(double leftValue, double rightValue, boolean squaredInputs) {
    	// This function is a wrapper in case we need to do anything special before calling the final TankDrive.
    	// New for 2018, the WPILIB drivetrain is redesigned and assumes positive == forwards so no Y-axis sign shenanigans anymore!
    	
    	differentialDrive1.tankDrive(leftValue, rightValue, squaredInputs);
    	
    }
    
    public void selectableDriveWithJoysticks(Joystick joyLeft, Joystick joyRight) {
		// Extract the joystick values
		double joyLeftX, joyLeftY, joyRightX, joyRightY;

		// If an Xbox controller, try using the two sticks on controller 0 (Left side) instead of using two joysticks		
		if (DriverStation.getInstance().getJoystickIsXbox(joyLeft.getPort())) {// if Xbox, it's probably the only input and would be on input0.
			joyLeftX = joyLeft.getRawAxis(0);  // Left stick X
			joyLeftY = joyLeft.getRawAxis(1);  // Left stick Y
			joyRightX = joyLeft.getRawAxis(4); // Right stick X
			joyRightY = joyLeft.getRawAxis(5); // Right stick Y
		}
		else {
			joyLeftX  = joyLeft.getX();
			joyLeftY  = joyLeft.getY();
			joyRightX = joyRight.getX();
			joyRightY = joyRight.getY();
		}

		// Print the raw joystick inputs
		//System.out.println("Raw Values:  joyLeftY="+joyLeftY+" joyLeftX="+joyLeftX + " joyRightY="+joyRightY+" joyRightX="+joyRightX);
		SmartDashboard.putNumber("JoyLX", joyLeftX);
		SmartDashboard.putNumber("JoyLY", joyLeftY);
		SmartDashboard.putNumber("JoyRX", joyRightX);
		SmartDashboard.putNumber("JoyRY", joyRightY);
		
		// Apply the 'dead zone' guardband to the joystick inputs:
		// Centered joysticks may not actually read as zero due to spring variances.
		// Therfore, remove any small values as being "noise".
		double joystickDeadzone = SmartDashboard.getNumber("Joystick Deadzone", 0); // default to zero if entry not found
		if (Math.abs(joyLeftX) < joystickDeadzone)
			joyLeftX = 0;
		if (Math.abs(joyLeftY) < joystickDeadzone)
			joyLeftY = 0;
		if (Math.abs(joyRightX) < joystickDeadzone)
			joyRightX = 0;
		if (Math.abs(joyRightY) < joystickDeadzone)
			joyRightY = 0;

		// Choose whether we square the inputs (for increased joystick sensitivity at low speeds) based on SmartDashboard settings.
    	boolean squaredInputs = SmartDashboard.getBoolean("SquaredInputs", true); // Default to true if setting not found

		// Find out which operating mode is requested and send the appropriate joystick values to the appropriate sub-function
		// We could access the local mode variable, but better to use an accessor function to hide implementation details
		if (this.isInTankMode()) {
			// We call the "local" wrapper, which uses programming assumptions that FWD = positive.		
			// However, because the joystick Y axis "up" is negative, we swap the sign on both left and right
			this.tankDrive(-joyLeftY, -joyRightY, squaredInputs); // Tank uses Y axis of left and right joysticks as independent left and right wheel controls
		}
		// Because we may add more drive modes in the future, use specific accessor functions rather than relying on assumptions of implementation.
		else if (this.isInArcadeMode()) {
			// We call the "local" wrapper, which uses programming assumptions that FWD = positive and Clockwise = positive.			
			// However, because the joystick Y axis "up" is negative, we swap the sign on that Y axis only.
			this.arcadeDrive(-joyRightY, joyRightX, squaredInputs); // Arcade uses one joystick:  Y axis for forward/backwards, and X axis for spin cw+/ccw-
		}
		// Error check.  If we have corrupted the mode somehow, and don't match any option, default to tank
		else {
			System.err.println("selectableDrive error:  Unknown mode detected.  Defaulting to Tank.");
			this.setTankMode();
			this.tankDrive(-joyLeftY, -joyRightY, squaredInputs); // See rules above for sign calculation.
		}
    }
    
    // Function to stop the robot
    public void stop() {
    	differentialDrive1.stopMotor();
    }
    
    // Function to put us in tank mode (and update Smart Dashboard indicator)
    // Hides boolean implementation from users
    public void setTankMode() {
    	m_isInTankMode = true;
    	SmartDashboard.putString("Drivetrain Mode", "TANK");
    }
    
    // Function to hide boolean implmentation from users
    public boolean isInTankMode() {
    	return m_isInTankMode;
    }
    
    // Function to put us in tank mode (and update Smart Dashboard indicator)
   public void setArcadeMode() {
    	m_isInTankMode = false;
    	SmartDashboard.putString("Drivetrain Mode", "ARCADE");
    }
    
   // Function to hide boolean implmentation from users
   public boolean isInArcadeMode() {
	   // Because current implentation is a single boolean, if we aren't in tank mode...we're in arcade mode.
	   return !m_isInTankMode;
   }
   
   @Override
   /* This function is invoked periodically by the PID Controller, */
   /* based upon navX MXP yaw angle input and PID Coefficients.    */
   public void pidWrite(double output) {
       m_rotateToAngleRate = output;
   }
   
   public void setSmallTurnPID() {
	   drivelineController.setPID(kSmallTurnP, kSmallTurnI, kSmallTurnD, kSmallTurnF);
	   drivelineController.setOutputRange(-kSmallTurnPIDOutputMax, kSmallTurnPIDOutputMax); // What is the allowable range of values to send to the output (our motor rotation)
   }
   
   public void setMedTurnPID() {
	   drivelineController.setPID(kMedTurnP, kMedTurnI, kMedTurnD, kMedTurnF);
	   drivelineController.setOutputRange(-kMedTurnPIDOutputMax, kMedTurnPIDOutputMax); // What is the allowable range of values to send to the output (our motor rotation)
   }

   public void setLargeTurnPID() {
	   //System.out.println("TurnP from Dashboard = " + SmartDashboard.getNumber("TurnP", 0.14));
	   drivelineController.setPID(kLargeTurnP, kLargeTurnI, kLargeTurnD, kLargeTurnF);
	   drivelineController.setOutputRange(-kLargeTurnPIDOutputMax, kLargeTurnPIDOutputMax); // What is the allowable range of values to send to the output (our motor rotation)
   }

	
    public double getTx() {
    	return tx.getDouble(0);
    }

    public double getTy() {
    	return ty.getDouble(0);
    }


	// Member Variables
    boolean m_isInTankMode = false; // true = tank; false = arcade
    public boolean absolute = true; //functions can use this as a parameter to the Turn command
    public boolean relative = false; //functions can use this as a parameter to the Turn command
    public boolean m_lateInitHasRun = false; //Flag to cause the lateInit function to be run only once (called from both teleop and autonomous init routines)

    //--------------------------------
    // SW PID subsystem variables
    //--------------------------------
    public PIDController drivelineController; // Use this PID controller to accomplish turns and track straight when driving forward.
    public double m_rotateToAngleRate; // PID output tells us how much to rotate to reach the desired setpoint target.
    
    //Limelight connections
    NetworkTable table;
    NetworkTableEntry tx;
    NetworkTableEntry ty;
    NetworkTableEntry ta;

    /* The following Software PID Controller coefficients will need to be tuned */
    /* to match the dynamics of your drive system.  Note that the      */
    /* SmartDashboard in Test mode has support for helping you tune    */
    /* controllers by displaying a form where you can enter new P, I,  */
    /* and D constants and test the mechanism.                         */
    
    public static final double kEncoderTicksPerInch = (4096 / (3.1415 * 6)); // 4096 encoder ticks per revolution; wheel diameter is nominally 6"
    static final double kToleranceDegrees = 0.25; // Stop if we are within this many degrees of the setpoint.
    public static final double kToleranceDistUnits = (int) 1/*inches*/ * kEncoderTicksPerInch; // stop if we are within this many encoder units of our setpoint.  18.85 inches/rev and 4096 ticks/rev means .25" is ~50 encoder ticks

    static final double kLargeTurnP = 0.0165;
    static final double kLargeTurnI = 0.00; //0.001504;
    static final double kLargeTurnD = 0.00;
    static final double kLargeTurnF = 0.00;
    public static final double kLargeTurnPIDOutputMax = 0.55; // Max motor output in large PID mode 0.55

    public static final double kMedTurnPIDLimit = 15.0; // Errors smaller than this number of degrees should use the medium PID profile
    static final double kMedTurnP = 0.2; //use a very large (relative to normal) P to guarantee max motor output .25
    static final double kMedTurnI = 0.00;
    static final double kMedTurnD = 0.05;
    static final double kMedTurnF = 0.00;
    public static final double kMedTurnPIDOutputMax = 0.225; // Max motor output in medium PID mode

    public static final double kSmallTurnPIDLimit = 1.5; // Errors smaller than this number of degrees should use the small PID profile
    static final double kSmallTurnP = 0.5; //use a very large (relative to normal) P to guarantee max motor output
    static final double kSmallTurnI = 0.00;
    static final double kSmallTurnD = 0.05;
    static final double kSmallTurnF = 0.00;
    public static final double kSmallTurnPIDOutputMax = 0.1475; // Max motor output in small PID mode

    /* Hardware PID values for the Talon */
    static final double kDistP = 0.15;
    static final double kDistI = 0.0;//0.005 on 2017 robot
    static final double kDistD = 0.0;
    static final double kDistF = 0.0; // Use 0.3789 for MotionMagic
}

