// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.PowerUp2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftMotor;
    public static WPI_TalonSRX driveTrainRightMotor;
    public static DifferentialDrive driveTrainDifferentialDrive1;
    public static SpeedController driveTrainLeftMotorPractice;
    public static SpeedController driveTrainRightMotorPractice;
    public static DifferentialDrive driveTrainDifferentialDrivePractice;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new WPI_TalonSRX(0);
        
        
        driveTrainRightMotor = new WPI_TalonSRX(1);
        
        
        driveTrainDifferentialDrive1 = new DifferentialDrive(driveTrainLeftMotor, driveTrainRightMotor);
        LiveWindow.addActuator("DriveTrain", "Differential Drive 1", driveTrainDifferentialDrive1);
        driveTrainDifferentialDrive1.setSafetyEnabled(true);
        driveTrainDifferentialDrive1.setExpiration(0.1);
        driveTrainDifferentialDrive1.setMaxOutput(1.0);

        driveTrainLeftMotorPractice = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "LeftMotorPractice", (Victor) driveTrainLeftMotorPractice);
        driveTrainLeftMotorPractice.setInverted(false);
        driveTrainRightMotorPractice = new Jaguar(1);
        LiveWindow.addActuator("DriveTrain", "RightMotorPractice", (Jaguar) driveTrainRightMotorPractice);
        driveTrainRightMotorPractice.setInverted(false);
        driveTrainDifferentialDrivePractice = new DifferentialDrive(driveTrainLeftMotorPractice, driveTrainRightMotorPractice);
        LiveWindow.addActuator("DriveTrain", "Differential Drive Practice", driveTrainDifferentialDrivePractice);
        driveTrainDifferentialDrivePractice.setSafetyEnabled(true);
        driveTrainDifferentialDrivePractice.setExpiration(0.1);
        driveTrainDifferentialDrivePractice.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS   
    }
}
