// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.PowerUp2018;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftMotor;
    public static WPI_TalonSRX driveTrainLeftFollower;
    public static SpeedControllerGroup driveTrainSpeedControllerGroupLeft;
    public static WPI_TalonSRX driveTrainRightMotor;
    public static WPI_TalonSRX driveTrainRightFollower;
    public static SpeedControllerGroup driveTrainSpeedControllerGroupRight;
    public static DifferentialDrive driveTrainDifferentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new WPI_TalonSRX(1);
        
        
        driveTrainLeftFollower = new WPI_TalonSRX(3);
        
        
        driveTrainSpeedControllerGroupLeft = new SpeedControllerGroup(driveTrainLeftMotor, driveTrainLeftFollower  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group Left", driveTrainSpeedControllerGroupLeft);
        
        driveTrainRightMotor = new WPI_TalonSRX(2);
        
        
        driveTrainRightFollower = new WPI_TalonSRX(4);
        
        
        driveTrainSpeedControllerGroupRight = new SpeedControllerGroup(driveTrainRightMotor, driveTrainRightFollower  );
        LiveWindow.addActuator("DriveTrain", "Speed Controller Group Right", driveTrainSpeedControllerGroupRight);
        
        driveTrainDifferentialDrive1 = new DifferentialDrive(driveTrainSpeedControllerGroupLeft, driveTrainSpeedControllerGroupRight);
        LiveWindow.addActuator("DriveTrain", "Differential Drive 1", driveTrainDifferentialDrive1);
        driveTrainDifferentialDrive1.setSafetyEnabled(true);
        driveTrainDifferentialDrive1.setExpiration(0.1);
        driveTrainDifferentialDrive1.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS   
    }
}
